# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9129bd9e891df38161785d849ab7c496"
name = "scribe-app"
handle = "scribe-app"
application_url = "https://demonstrated-designation-occurs-columbus.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "scribe-ai.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://demonstrated-designation-occurs-columbus.trycloudflare.com/auth/callback",
  "https://demonstrated-designation-occurs-columbus.trycloudflare.com/auth/shopify/callback",
  "https://demonstrated-designation-occurs-columbus.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
